---
  - apt: update_cache=yes cache_valid_time=3600
    become: yes
    when: ansible_pkg_mgr == "apt"
    tags: install

  - include_vars: "{{ item }}"
    with_first_found:
      - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int }}.yml"
      - "../vars/{{ ansible_distribution }}.yml"
      - "../vars/{{ ansible_os_family }}.yml"
      - "../vars/default.yml"
    when: virtualenv_package_name is not defined
    tags: install

  - debug:
      var: letsencrypt_command

  - name: install certbot (Debian jessie)
    include: debian-jessie.yml
    when: ansible_distribution == "Debian" and ansible_distribution_release == "jessie"

  - name: install certbot (Debian stretch)
    include: debian-stretch.yml
    when: ansible_distribution == "Debian" and ansible_distribution_release == "stretch"

  - name: install certbot (using pip)
    include: notdebian.yml
    when: ansible_distribution != "Debian"

  - name: Ensure webroot directories exist
    file:
      path: "{{ letsencrypt_webroot_path }}/{{ item.name }}"
      state: directory
      follow: yes
    become: yes
    with_items: "{{ letsencrypt_cert_domains }}"

  - name: Attempt to get the certificate using the webroot authenticator
    command: "{{ letsencrypt_command }}  {% for domain in item.urls %}-d {{ domain }} {% endfor %}-a webroot --webroot-path {{ letsencrypt_webroot_path }}/{{ item.name }} certonly"
    become: yes
    args:
      creates: "/etc/letsencrypt/live/{{ item.name }}"
    ignore_errors: True
    with_items: "{{ letsencrypt_cert_domains }}"

  - name: Fix the webroot map in the renewal file
    ini_file:
      section: "[webroot_map]"
      option: "{{ item.name }}"
      value: "{{ letsencrypt_webroot_path }}//{{ item.name }}"
      dest: "/etc/letsencrypt/renewal/{{ item.name }}.conf"
    become: yes
    with_items: "{{ letsencrypt_cert_domains }}"

  - name: Install renewal cron
    become: yes
    cron:
      name: "Let's Encrypt Renewal"
      day: "{{ letsencrypt_renewal_frequency.day }}"
      hour: "{{ letsencrypt_renewal_frequency.hour }}"
      minute: "{{ letsencrypt_renewal_frequency.minute }}"
      job: "{{letsencrypt_path}} renew --quiet {{ letsencrypt_renewal_command_args }}"
